package com.jelte.norii.audio;

public enum AudioCommand {
	MUSIC_LOAD, MUSIC_PLAY_ONCE, MUSIC_PLAY_LOOP, MUSIC_STOP, MUSIC_STOP_ALL, SOUND_LOAD, SOUND_PLAY_ONCE, SOUND_PLAY_LOOP, SOUND_STOP, MUSIC_PAUSE, MUSIC_RESUME
}