package com.jelte.norii.magic;

public enum ModifiersEnum {
	DAMAGE_OVER_TIME, REMOVE_AP, REDUCE_ARMOR, REDUCE_DAMAGE, IMPROVE_DAMAGE, STUNNED, ROOTED, SILENCED, IMAGE_CHANGED, OUT_OF_GAME, INVISIBLE;
}
