package com.jelte.norii.magic;

public enum ModifiersEnum {
	DAMAGE_OVER_TIME_PHYSICAL, DAMAGE_OVER_TIME_MAGICAL, BUFF_PHYSICAL_DAMAGE, BUFF_MAGICAL_DAMAGE, REMOVE_AP, REDUCE_PHYSICAL_DEFENSE, REDUCE_MAGICAL_DEFENSE, REDUCE_DAMAGE, IMPROVE_DAMAGE, STUNNED, ROOTED, SILENCED, IMAGE_CHANGED, OUT_OF_GAME, INVISIBLE, PURE_DAMAGE, LINKED;
}
