package com.jelte.norii.battle;

public enum MessageToBattleScreen {
	UNIT_ACTIVE,
	UPDATE_UI,
	SET_CHARACTER_HUD,
	UNSET_CHARACTER_HUD,
	CLICKED,
	PLAYER_WINS,
	AI_WINS,
	AI_FINISHED_TURN,
	FOCUS_CAMERA,
	UPDATE_POS,
	SHOW_STATUS_UI,
	HIDE_STATUS_UI,
	HIDE_ACTIONS,
	REMOVE_HUD_UNIT,
	ADD_UNIT_UI,
	ADD_UNIT_ENTITYSTAGE,
	UPDATE_HP_UNIT,
	MOVING_ENTITY,
	UNIT_DIED,
	ACTION_COMPLETED,
	LOCK_UI,
	UNLOCK_UI,
	AI_FINISHED_CALCULATING
}
