package com.jelte.norii.battle;

public enum MessageToBattleScreen {
	UNIT_ACTIVE, CANCEL_ACTION, UPDATE_UI, SET_CHARACTER_HUD, UNSET_CHARACTER_HUD, CLICKED, PLAYER_WINS, AI_WINS, AI_FINISHED_TURN, FOCUS_CAMERA, UPDATE_POS, SHOW_STATUS_UI, HIDE_STATUS_UI
}
