package com.jelte.norii.ui;

public enum HudMessageTypes {
	INVALID_ATTACK_TARGET,
	INVALID_MOVE,
	INVALID_SPAWN_POINT,
	INVALID_SPELL_TARGET,
	NOT_ENOUGH_AP,
	NUMBER_OF_UNITS_DEPLOYED,
	PLAYER_VICTORY,
	AI_VICTORY,
	DEPLOY_UNITS_INFO,
	SELECT_UNIT_INFO,
	EXPLAIN_ACTION_INFO,
	EXPLAIN_TURNING_INFO,
	EXPLAIN_END_TURN_INFO,
	EXPLAIN_CANCEL_INFO,
	EXPLAIN_WIN_LOSE_INFO,
	PLAYER_TURN,
	ENEMY_TURN
}
